name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: OSSRH_GPG_SECRET_KEY_PASSWORD
          cache: 'maven'

      - name: Get Tag Name
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Deploy
        run: ./mvnw -B clean deploy -P sign --no-transfer-progress --batch-mode
        env:
          OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref }} \
            --title "Release ${{ github.ref }}"

      - name: Update README.md
        run: |
          sed -i "s/<LATEST_RELEASE_VERSION_HERE>/${{ env.TAG_NAME }}/g" README.md

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a new branch
        run: |
          git checkout -b update-readme-${{ env.TAG_NAME }}
          git add README.md
          git commit -m "Update README with latest release version ${{ env.TAG_NAME }}"
          git push origin update-readme-${{ env.TAG_NAME }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-readme-${{ env.TAG_NAME }}
          title: Update README with latest release version ${{ env.TAG_NAME }}
          body: Automatically generated update for the latest release version in README.
          base: main
