name: update-readme-version

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get latest release tag
        id: get_release
        run: echo "::set-output name=version::${GITHUB_REF##*/}"

      - name: Update README.md
        run: |
          sed -i "s/<LATEST_RELEASE_VERSION_HERE>/${{ steps.get_release.outputs.version }}/g" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with latest release version ${{ steps.get_release.outputs.version }}"
          git push
